apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: dockerhub.thalamus.am/spring:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: nexus

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring
  name: spring
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: spring
  type: LoadBalancer
